name: 'Upload TestFlight Release Notes'
description: 'A GitHub Action to upload TestFlight Release Notes for a particular build number'

inputs:
  ISSUER_ID:
    description: 'Issuer Id from AppStore Connect'
    required: true
  KEY_ID:
    description: 'Key ID from AppStore Connect'
    required: true
  PRIVATE_KEY:
    description: 'Private Key from AppStore Connect'
    required: true
  APP_ID:
    description: 'App ID from AppStore Connect'
    required: true
  WHATS_NEW:
    description: 'The text you want to set on the build'
    required: true
  BUILD_NUMBER:
    description: 'The build number to target'
    required: true

runs:
  using: 'composite'  # Use composite action to avoid Docker
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

#     - name: Set up Python
#       uses: actions/setup-python@v5
#       with:
#         python-version: '3.10'

    - name: Setup virtual environment
      shell: bash
      run: |
        echo "Current directory: $(pwd)"
        mkdir -p ${{ github.workspace }}/api_venv
        cd ${{ github.workspace }}/api_venv
        python3 -m venv venv
        source venv/bin/activate
        pip3 install cryptography                                
        pip3 install requests
        pip3 install pyjwt
        python3 ./main.py

#     - name: Install dependencies
#       shell: bash
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt

#     - name: Run TestFlight Upload Script
#       shell: bash
#       run: |
#         python ./main.py

branding:
  icon: 'mic'
  color: 'blue'
