name: 'Upload TestFlight Release Notes'
description: 'A GitHub Action to upload TestFlight Release Notes for a particular build number'

inputs:
  ISSUER_ID:
    description: 'Issuer Id from AppStore Connect'
    required: true
  KEY_ID:
    description: 'Key ID from AppStore Connect'
    required: true
  PRIVATE_KEY:
    description: 'Private Key from AppStore Connect'
    required: true
  APP_ID:
    description: 'App ID from AppStore Connect'
    required: true
  WHATS_NEW:
    description: 'The text you want to set on the build'
    required: true
  BUILD_NUMBER:
    description: 'The build number to target'
    required: true

runs:
  using: 'composite'  # Use composite action to avoid Docker
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Setup virtual environment
      shell: bash
      run: |
        echo "Current directory: $(pwd)"
        # Create a temporary virtual environment directory
        VENV_DIR=$(mktemp -d)
        
        # Create and activate the virtual environment
        python3.10 -m venv "$VENV_DIR/venv"
        source "$VENV_DIR/venv/bin/activate"
        
        # Install requirements and run the script
        pip install -r "${{ github.workspace }}/requirements.txt"
        python "${{ github.workspace }}/main.py"

#     - name: Install dependencies
#       shell: bash
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt

#     - name: Run TestFlight Upload Script
#       shell: bash
#       run: |
#         python ./main.py

branding:
  icon: 'mic'
  color: 'blue'
